# Generated by Django 4.2.7 on 2023-11-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT store_collection(title)
        values('collection1')
        ""","""DELETE FROM store_collection
        WHERE title='collection1'""")
    ]
